### ISSUE TITLE
zfs status cmd fail

### ISSUE THREAD

**Issue by sachin11** [zfs-linux/zfs#90] opened 2011-01-10 18:44 UTC
<pre>
Steps :
1) Create zpool with four device 

#zpool create tank /dev/sda1 /dev/sdb1 /dev/sdc1 /dev/sde1

2) Check zpool list

[root@fedora-14-230 kqinfo]# zpool list
NAME   SIZE  ALLOC   FREE    CAP  DEDUP  HEALTH  ALTROOT
tank  1.16T  9.40M  1.16T     0%  1.00x  ONLINE  -

3)Check zpool status

[root@fedora-14-230 kqinfo]# zpool status
  pool: tank
 state: ONLINE
zpool: ../../cmd/zpool/zpool_main.c:3652: status_callback: Assertion `reason == ZPOOL_STATUS_OK' failed.
Aborted (core dumped)
[root@fedora-14-230 kqinfo]#
</pre>

**Comment by mitra** [comment] 2011-02-01 04:52
duplicate of issue#85

**Closed as completed by mitra** 2011-02-01 04:52 UTC
