### ISSUE TITLE
Cannot fsync() directory

### ISSUE THREAD

**Issue by ghost** [zfs-linux/zfs#99] opened 2011-01-16 08:27 UTC
When pass a directory fd to fsync(), -1 will be returned, errno will be set to EINVAL.

Some programs need this feature to function, for example the dpkg package manager.

**Comment by deepenmehta** [comment] 2011-01-20 11:26
Thanks for contacting KQ Stor support.

The problem is resolved now. It has been committed to lzfs's master branch.
We will be creating new rpm/deb packages and will upload on website.  Meanwhile you can build the code from the source and use it.

**Comment by mitra** [comment] 2011-02-01 04:54
fixed

**Closed as completed by mitra** 2011-02-01 04:54 UTC
Labels: resolved
