### ISSUE TITLE
Not able to run program on ZFS

### ISSUE THREAD

**Issue by ganeshjagtap** [zfs-linux/zfs#69] opened 2010-12-21 05:55 UTC
$ ls -l test.sh 
ls: test.sh: No such file or directory
-rwxr-xr-x 1 root root 12 2010-12-19 00:52 test.sh

$  cat test.sh 
echo "test"

$  ls -l 
ls: test.sh: No such file or directory
total 3
drwxr-xr-x 2 root root  8 2010-12-19 00:55 prime
-rwxr-xr-x 1 root root 12 2010-12-19 00:52 test.sh

$  ./test.sh 
bash: ./test.sh: No such file or directory

$ sh test.sh 
test

**Comment by ganeshjagtap** [comment] 2010-12-21 05:58
This is because of SE linux. The se linux has some features to prevent execution from file system unless certain setting are enabled. At the current moment these setting have not be tunned correctly which is causing this problem.
      This was suggested by Anand Sir.

**Comment by mitra** [comment] 2010-12-23 12:04
duplicate of issue 67

**Closed as completed by mitra** 2010-12-23 12:04 UTC
